before_script:
    - apt-get update
    - apt-get -y install mono-complete
    - wget https://www.nuget.org/nuget.exe
    - mono nuget.exe restore "ClassLibrary2.sln"

build:
 script:
    - xbuild  "ClassLibrary2.sln"